Lixulia-Case
SlimeVR/SlimeVR-Docs-Site pull request #146
Opened 2023-01-13 01:37 UTC by ZRock35

Adding Arcturus case to Cases section, also images.

2023-01-13 01:39 UTC, Louka3000 commented on diy/cases.md
> +[Github](https://github.com/Lixulia/Arcturus) (edited)
```suggestion
[Github](https://github.com/Lixulia/Arcturus)
```

2023-01-13 01:43 UTC, Louka3000 requested changes

2023-01-13 01:43 UTC, Louka3000 commented on diy/cases.md
> +![Case](https://github.com/Lixulia/Arcturus/blob/main/renderforarcturus.PNG) {: .caseImage}
```suggestion
![Case](https://raw.githubusercontent.com/Lixulia/Arcturus/main/renders/renderforarcturus.PNG) {: .caseImage}
```

2023-01-13 01:43 UTC, Louka3000 commented on diy/cases.md
> +[Github](https://github.com/Lixulia/Arcturus) (edited)
```suggestion
[Github](https://github.com/Lixulia/Arcturus)
```

2023-01-13 01:44 UTC, Louka3000 commented on diy/cases.md
> +[Github](https://github.com/Lixulia/Arcturus) (edited)
oops duplicate

2023-01-13 01:57 UTC, Louka3000 approved these changes

2023-01-15 06:51 UTC, calliePepper approved these changes

2023-01-15 06:51 UTC, merged