Add Adafruit BNO to Schematics
SlimeVR/SlimeVR-Docs-Site pull request #148
Opened 2023-01-19 22:08 UTC by ZRock35

Changed js file to include "ada" id, added two images for main and aux, added radio button and description to the main schematic page.

2023-01-19 22:43 UTC, Louka3000 requested changes
Please rename `ada` to `bno_ada`. What if we wanna add ICM Adarafruit IMUs to the docs (or any other IMU idk)?

Also in other pictures, the aux image doesn't have the main IMU since it's overlaid on top of it but that doesn't matter, just pointing it out

2023-01-19 22:43 UTC, Louka3000 commented on diy/tracker-schematics.md
> +   - <input id="ada" type="radio" name="d1-imu" value="ada"> <label for="ada">BNO085 (ADAFRUIT)</label> - Adafruit version of BNO085.
```suggestion
   - <input id="ada" type="radio" name="d1-imu" value="ada"> <label for="ada">BNO085 (Adarafruit)</label> - Adafruit version of BNO085.
```
Unless there's a reason to use it in all caps, I feel like lowercase is better?

2023-01-19 22:57 UTC, Louka3000 commented
Could you modify the images' names as well? And don't forget to modify it in schematics.js as well

2023-01-19 23:34 UTC, Louka3000 approved these changes

2023-01-20 04:02 UTC, calliePepper approved these changes

2023-01-20 04:03 UTC, merged