Update lime-slimes.md
SlimeVR/SlimeVR-Docs-Site pull request #162
Opened 2023-02-08 14:00 UTC by Loler920a

Updated description
Replaced legacy name
Officially announce the end of active development (Really has ended quite sometime ago TBH)

2023-02-12 00:24 UTC, calliePepper requested changes

2023-02-18 02:00 UTC, calliePepper commented
Could you pull in the small change from main? I pulled the logo onsite in the last PR

2023-02-21 06:30 UTC, Rosdayle commented
> ould you pull in the small change from main? I pulled the logo onsite in the last PR

?

2023-02-21 15:47 UTC, closed without merging

2023-02-21 15:48 UTC, Rosdayle commented
Closed will push again for new doc additions/layout