Add "Updating Your Tracker's Firmware" page
SlimeVR/SlimeVR-Docs-Site pull request #271
Opened 2024-03-26 20:21 UTC by kounocom

2024-03-26 20:54 UTC, TheDevMinerTV requested changes

2024-03-26 20:54 UTC, TheDevMinerTV commented on src/updating-firmware.md
> +7. Press Flash to Device, and select your tracker in the pop-up, which should appear as `USB Serial`.
The tracker has to be off and connected, it'll show up in the Serial dropdown anyways.
When the flashing is waiting, the tweezers need to pressed on the pads and the shielding, while turning on the tracker, after which the web flasher should continue.

2024-03-26 20:54 UTC, TheDevMinerTV commented on src/updating-firmware.md
> +The currently recommended version of firmware for Official trackers is v0.4.0.
```suggestion
There are two ways to update the firmware on official SlimeVR trackers: OTA (over-the-air) or via USB.

The currently recommended version of firmware for official trackers is v0.4.0.
```

2024-03-26 20:54 UTC, TheDevMinerTV commented on src/updating-firmware.md
> +This method is the simplest, and doesn't require any cables or disassembly, but it does require your tracker to already be paired to your Wi-Fi network.
```suggestion
This method is the simplest, and doesn't require any cables or disassembly, but it does require your tracker to already be paired to your Wi-Fi network and has the potential to mess up your tracker. If it does, please refer to the USB flashing section below.
```

2024-03-30 18:51 UTC, Eirenliel approved these changes
Good start but we need more warnings and clarity in some of this. I think it's okay to merge as is rn.

2024-03-30 18:51 UTC, merged