Update imu-calibration.md
SlimeVR/SlimeVR-Docs-Site pull request #274
Opened 2024-04-10 20:19 UTC by TuistoVRC

Lots of people don't have a 3d printer, the 3d printer steps were to minimalistic. Created a more detailedhairdryer procedure :-) and a link from Ilyasnow, who helped me with

2024-04-10 21:09 UTC, ImUrX requested changes
please use markdown

2024-04-10 21:09 UTC, ImUrX commented on src/server/imu-calibration.md
> +-With a 3d printer
```suggestion
#### With a 3d printer
```

2024-04-10 21:09 UTC, ImUrX commented on src/server/imu-calibration.md
> +-With a hairdryer
```suggestion
#### With a hairdryer
```

2024-04-10 21:09 UTC, ImUrX commented on src/server/imu-calibration.md
> +
```suggestion
1. Place your tracker in a fridge or freezer for a short period of time(about 10 minutes) to cool it down to below 15°C. 
1. Get the tracker out and put it on a stable underground.
   - Open the SlimeVR app -> Turn on developer mode -> In home at the bottom-right toggle more info, to see all details about your slime and it's temperature.
   - Turn it on and let it sit until it reaches operating temperatures naturally; Don't use a hairdryer yet! When you put your tracker closer to your computer you can reach a higher temperature quicker.
1. Wait until your tracker's temperature levels out. Warm it up with your hairdryer to around 43°C, do not reach 45°C yet.
1. Let it cool down naturally to operating temperature again.
1. 30 degrees? Airdry it to 46 degrees to squeeze out the last points for your TCAL and let it cool down.
1. Check if you did well with the [USB WebUI checking tool](https://ilyasnow.github.io/TCAL-Checker/)

```

2024-04-12 12:40 UTC, chennbru commented
> please use markdown

Thank you for adjusting. Is it ok like this? And is it ready?

2024-09-04 02:27 UTC, ButterscotchV requested changes
I think a bit of clean-up could help and it should be good

2024-09-04 02:27 UTC, ButterscotchV commented on src/server/imu-calibration.md
> +1. Place your tracker in a fridge or freezer for a short period of time(about 10 minutes) to cool it down to below 15°C.
```suggestion
1. Place your tracker in a fridge or freezer for a short period of time (about 10 minutes) to cool it down to below 15°C. 
```

2024-09-04 02:27 UTC, ButterscotchV commented on src/server/imu-calibration.md
> +   - Open the SlimeVR app -> Turn on developer mode -> In home at the bottom-right toggle more info, to see all details about your slime and it's temperature.
```suggestion
1. Take the tracker out and put it on a stable surface like a table.
   - Open the SlimeVR app -> Turn on developer mode -> One the home tab at the bottom-right, toggle "More info" to see all details about your Slime and it's temperature.
```

2024-09-04 02:27 UTC, ButterscotchV commented on src/server/imu-calibration.md
> +1. 30 degrees? Airdry it to 46 degrees to squeeze out the last points for your TCAL and let it cool down.
```suggestion
1. Once around 30°C, use the hairdryer to get it to around 46°C to finish measuring the last points for your TCAL, then let it cool down.
```

2024-09-04 02:27 UTC, ButterscotchV commented on src/server/imu-calibration.md
> +#### With a hairdryer
```suggestion
#### With a hairdryer

```

2024-09-04 02:27 UTC, ButterscotchV commented on src/server/imu-calibration.md
> +#### With a 3d printer
```suggestion
#### With a 3d printer

```

2025-04-17 17:58 UTC, Smeltie commented on src/server/imu-calibration.md
> +   - Open the SlimeVR app -> Turn on developer mode -> In home at the bottom-right toggle more info, to see all details about your slime and it's temperature.
I would rename home tab to home page

2025-04-28 02:42 UTC, calliePepper approved these changes

2025-04-28 02:46 UTC, ShineBrightMeow approved these changes

2025-06-15 23:43 UTC, merged