Create MacOS Installation.md
SlimeVR/SlimeVR-Docs-Site pull request #316
Opened 2024-12-19 01:58 UTC by Sigtyr-1

Made some instructions for MacOS install. First time using Github so apologies if I'm doing it wrong!

2025-03-18 21:14 UTC, ButterscotchV requested changes
This guide seems alright, just some minor formatting and structure things. We still need a guide here, correct?

2025-03-18 21:14 UTC, ButterscotchV commented on src/tools/MacOS Installation.md
> +<img width="268" alt="warning" src="https://github.com/user-attachments/assets/018db046-56bc-4b74-9104-5a92e8d77408" />
All these images should be added to the docs resources and linked from the docs site itself rather than a hard link to GitHub. See how images are done in [./src/quick-setup.md](https://github.com/SlimeVR/SlimeVR-Docs-Site/blob/main/src/quick-setup.md) for reference.

2025-03-18 21:14 UTC, ButterscotchV commented on src/tools/MacOS Installation.md
> +# Installing Java
There should only be one title header (`#`) in the page, for any sub-headers, start with a secondary header (`##`).

2025-03-18 21:14 UTC, ButterscotchV commented on src/tools/MacOS Installation.md
> +### 1. Download
These steps should start with a secondary header, perhaps something like `## Installation steps`?

2025-04-17 17:51 UTC, Smeltie commented on src/tools/MacOS Installation.md
> +# Installing Java
I have fixed these for now

2025-04-17 17:51 UTC, Smeltie commented on src/tools/MacOS Installation.md
> +### 1. Download
Fixed this for now

2025-04-17 17:53 UTC, Smeltie commented
@Sigtyr-1 I made some changes and fixes, can you verify this is all still relevant and wrap up the final section even if it's just a "and now you're done" kind of section.
I don't have a mac so I can verify this works/is still applicable.

2025-04-17 18:04 UTC, ShineBrightMeow approved these changes
The guide looks good to me. I don't have experience with Macs to verify each step.

2025-04-17 18:04 UTC, ShineBrightMeow commented on src/tools/MacOS Installation.md
> +Go to System Settings - > Privacy and Security -> You should see SlimeVR was blocked as shown below. Click Open Anyway.
```suggestion
Go to System Settings - > Privacy and Security -> You should see SlimeVR was blocked as shown below. Click "Open Anyway". 

```

2025-04-17 18:04 UTC, ShineBrightMeow commented on src/tools/MacOS Installation.md
> +Go to System Settings - > Privacy and Security -> Scroll to the bottom -> Security -> Allow accessories to connect: Change this to Automatically When Unlocked.
```suggestion
Go to System Settings - > Privacy and Security -> Scroll to the bottom -> Security -> Allow accessories to connect: Change this to "Automatically When Unlocked".

```

2025-04-17 18:04 UTC, ShineBrightMeow commented on src/tools/MacOS Installation.md
> +Open SlimeVR and follow the Setup Guide to connect a tracker. You may run into the below message. Click Allow to connect trackers.
```suggestion
Open SlimeVR and follow the Setup Guide to connect a tracker. You may run into the below message. Click "Allow" to connect trackers. 

```

2025-04-18 01:29 UTC, ButterscotchV approved these changes

2025-04-22 20:24 UTC, ShineBrightMeow approved these changes

2025-04-24 18:01 UTC, merged