Some elbow tracking info
SlimeVR/SlimeVR-Docs-Site pull request #83
Opened 2022-03-16 23:23 UTC by Louka3000

TODO:
- Component lists page
- Body proportion image (with purple person)

2022-03-16 23:26 UTC, Louka3000 commented
Can merge this PR now btw.

Current component lists page seems to only work with 5 full trackers, then it just adds more IMUs.
I know some Javascript but I'd prefer someone else with more experience to do it :p 
As for the body proportion image, I'd like @calliePepper to help make pictures :3

2022-03-17 09:45 UTC, calliePepper approved these changes
Amazing, now I gotta make a little picture :3

2022-03-17 13:36 UTC, Eirenliel requested changes

2022-03-17 13:36 UTC, Eirenliel commented on server-setup/body-config.md
> +Shake your head left to right as if you’re disagreeing. Adjust your head offset until any movement is be negligible. All trackers should stay in place.
```suggestion
Shake your head left to right as if you’re disagreeing. Adjust your head offset until any movement is negligible. All trackers should stay in place. 
```

2022-03-17 13:36 UTC, Eirenliel commented on server-setup/body-config.md
> +Move your head up and down as if you’re nodding OR move head side-to-side as if you're confused. Adjust your neck length until any movement is be negligible. All trackers should stay in place.
```suggestion
Move your head up and down as if you’re nodding OR move head side-to-side as if you're confused. Adjust your neck length until any movement is negligible. All trackers should stay in place.
```

2022-03-17 13:37 UTC, Eirenliel approved these changes

2022-03-17 13:37 UTC, merged