Updated ICM-20948 to cover some faqs.
SlimeVR/SlimeVR-Docs-Site pull request #96
Opened 2022-05-24 20:18 UTC by ThreadOfFate

Hopefully this will better cover some the faqs on the ICM-20948.

2022-05-30 06:42 UTC, Smeltie requested changes
Line 129:
There are quite a few variants of the ICM-20948, most of which operate at 3.3v.

Line 133:
 please note this board requires you to bridge SD0 to GND to change the address

2022-05-30 06:43 UTC, Smeltie commented
@ThreadOfFate Please check and consider the suggested changes.
2 minor fixes and wording changes for better readability and to correct the sentences.

2022-05-30 15:24 UTC, ThreadOfFate reviewed
Requested changes were applied.

2022-06-11 01:16 UTC, calliePepper approved these changes

2022-06-11 01:19 UTC, merged